##    Last Edited: 1.2.13   	
##   	pete.mohanty@gmail.com

# converts mohantydata.RData
# into data frames that can be used for regression, etc
# Consensus and Polarization and Net Change papers

# creates two datasets - one group level ("groupleveldataframe.rdata")
#                     - one individual level ("indleveldataframe.rdata")

# converts all DPs in mohantydata except for EU, BTP 2003, BTP 2005, San Mateo

# to-do: add JAPAN

library(foreign)

setwd("c:/users/pete/dropbox/cdd/2012")
source("hlmFunc.R") # Loading up functions

rescale <- function(original, newmin=0, newmax=1){
  # if original contains NAs, returns as NA  
  zero.one <- (original - min(original, na.rm = TRUE))/(max(original, na.rm = TRUE) - min(original, na.rm = TRUE))
  return((zero.one*(newmax - newmin)) + newmin)
}

oneistrue <- function(PK.array){
  # if "one" is true, but false isn't zero or there are still missing items to be coded to zero  
  return(ifelse(!is.na(PK.array),  ifelse(PK.array==1, 1, 0), 0))
}


make.data <- function(t1att, t2att, poll, FP, issue, local, salience.T1PK){
  # group level data  
  
  att.t1 <- subset(t1att, pollname==poll)
  att.t2 <- subset(t2att, pollname==poll)
  att.t1 <- ifelse(is.na(att.t1), .5, att.t1)
  att.t2 <- ifelse(is.na(att.t2), .5, att.t2)
  
  know.t1 <- subset(t1know, pollname==poll)
  group <- subset(pollgroup, pollname==poll)
  
  change.i <- att.t2 - att.t1
  abs.net.change <- abs(by(change.i, group, mean))
  
  homogenization <- -(by(att.t2, group, sd) - by(att.t1, group, sd))
  
  d <- ifelse(by(att.t1, group, mean) > .5, 1, -1)  
  polarized <- d * (by(att.t2, group, mean) - by(att.t1, group, mean))
  
  salience.T1PK.by.group <- by(know.t1, group, mean)
  diversity <- by(att.t1, group, sd)
  extremity <- abs(.5 - by(att.t1, group, mean))

  online <- unique(ifelse(subset(mode, pollname==poll) == 1, 1, 0))
  US <- unique(ifelse(subset(country, pollname==poll) == 1, 1, 0))
  country <- unique(subset(country, pollname==poll))
  cp.paper <- unique(subset(polarization, pollname==poll))
  netchange.paper <- unique(subset(netchange, pollname==poll))
  poll.id <- unique(subset(pollid, pollname==poll))

  group <- sort(unique(group))
  
  return(cbind(homogenization, polarized, abs.net.change, group, salience.T1PK, diversity, 
               extremity, online, US, FP, country, salience.T1PK.by.group, issue, cp.paper, 
               netchange.paper, local, poll.id))
  
}  


make.data.i <- function(t1att, t2att, poll, FP, issue, local, salience.T1PK){
# individual level data
  # ommitting polarization and homogenization for now  
  # would need to reconceptualize as individual level variables
  
  t1att <- subset(t1att, pollname==poll)
  t1att <- ifelse(is.na(t1att), .5, t1att)
  
  t2att <- subset(t2att, pollname==poll)
  t2att <- ifelse(is.na(t2att), .5, t2att)
  
  net.change <- abs(t2att - t1att)
  
  group <- subset(pollgroup, pollname==poll)
  
  this.pollgroup <- subset(pollgroup, pollname==poll)
  salience.to.group.T1PK <- matrix(nrow=nrow(as.matrix(net.change)))
  diversity <- matrix(nrow=nrow(as.matrix(net.change)))
  extremity <- matrix(nrow=nrow(as.matrix(net.change)))
  
  i <- 1
  for(i in 1:nrow(as.matrix(net.change))){
    salience.to.group.T1PK[i] <- mean(subset(t1know, this.pollgroup[i] == this.pollgroup))
    diversity[i] <- sd(subset(t1att, this.pollgroup[i] == this.pollgroup))
    extremity[i] <- abs(.5 - mean(subset(t1att, this.pollgroup[i]== this.pollgroup)))
  }
    
  salience.to.group.T1PK <- salience.to.group.T1PK
  diversity <- diversity
  extremity <- extremity
  
  online <- unique(ifelse(subset(mode, pollname==poll) == 1, 1, 0))
  US <- unique(ifelse(subset(country, pollname==poll) == 1, 1, 0))
  country <- unique(subset(country, pollname==poll))
  cp.paper <- unique(subset(polarization, pollname==poll))
  netchange.paper <- unique(subset(netchange, pollname==poll))
  poll.id <- unique(subset(pollid, pollname==poll))
  know.t1 <- subset(t1know, pollname==poll)
  know.t2 <- subset(t2know, pollname==poll)
  id <- subset(caseid, pollname==poll)
  
  return(cbind(net.change, group, salience.T1PK, diversity, 
               extremity, online, US, FP, country, salience.to.group.T1PK, issue, cp.paper, 
               netchange.paper, local, id, poll.id, know.t1, know.t2, t1att, t2att))
  
}  

# loading file generated by datacleaning2012.R
load("c:/users/pete/dropbox/cdd/data/mohantydata.rdata")
attach(master)


#################################################################################
################## DISCUSSION GROUP LEVEL DATA ##########################################
######################################################################################

#1  Australia Referendum
setwd("c:/users/pete/dropbox/cdd/data/Australia OZ/")
australia <- spss("australia.sav")

aus.salience.t1K <- mean(rowMeans(cbind(australia$qrfact1, australia$rpfact1, australia$jgfact1, 
                                        australia$ggfact1, australia$busfact1, australia$pfact1, australia$prfact1,
                                        australia$rfact1, australia$welfact1)), na.rm=TRUE)
remove(australia)

t1att <- aus.autind1
t2att <- aus.autind2
poll <- "AU Monarchy"

data <- make.data(aus.autind1, aus.autind2, poll="AU Monarchy", 0, 1, 0, aus.salience.t1K)  # national autonomy
data <- rbind(data, make.data(aus.demind1, aus.demind2, "AU Monarchy", 0, 2, 0, aus.salience.t1K)) # democracy
data <- rbind(data, make.data(aus.polind1, aus.polind2, "AU Monarchy", 0, 3, 0, aus.salience.t1K)) # politicization
data <- rbind(data, make.data(aus.tradind1, aus.tradind2, "AU Monarchy", 0, 4, 0, aus.salience.t1K)) #tradition
data <- rbind(data, make.data(aus.workind1, aus.workind2, "AU Monarchy", 0, 5, 0, aus.salience.t1K)) #workability


#2  Bulgaria 
setwd("c:/users/pete/dropbox/cdd/data/Bulgaria/Bulgaria_Data/")

bulgaria <- spss("delpoll_control_eng.sav")
bul.salience.T1K <- mean(rowMeans(cbind(oneistrue(bulgaria$q12_1), oneistrue(bulgaria$q12_2), 
                                   oneistrue(bulgaria$q12_3), oneistrue(bulgaria$q12_4), 
                                   oneistrue(bulgaria$q12_5), oneistrue(bulgaria$q12_6))))
remove(bulgaria)

data <- rbind(data, make.data(bulgaria.bulgaria.t1clibe, bulgaria.bulgaria.t2clibe, "Bulgaria", 0, 6, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q10_3, bulgaria.bulgaria.t2q10_3, "Bulgaria", 0, 7, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q16, bulgaria.bulgaria.t2q16, "Bulgaria", 0, 8, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q19, bulgaria.bulgaria.t2q19, "Bulgaria", 0, 9, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q21, bulgaria.bulgaria.t2q21, "Bulgaria", 0, 10, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q22, bulgaria.bulgaria.t2q22, "Bulgaria", 0, 11, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q23, bulgaria.bulgaria.t2q23, "Bulgaria", 0, 12, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q8_1, bulgaria.bulgaria.t2q8_1, "Bulgaria", 0, 13, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q8_11, bulgaria.bulgaria.t2q8_11, "Bulgaria", 0, 14, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q8_7, bulgaria.bulgaria.t2q8_7, "Bulgaria", 0, 15, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1q8_8, bulgaria.bulgaria.t2q8_8, "Bulgaria", 0, 16, 0, bul.salience.T1K))
data <- rbind(data, make.data(bulgaria.bulgaria.t1tghpc, bulgaria.bulgaria.t2tghpc, "Bulgaria", 0, 17, 0, bul.salience.T1K))


#3	China
setwd("C:/Users/pete/Dropbox/cdd/data/China/")
china <- spss("China Merged Dataset.sav")
china.salience.T1K <- mean(china$knowm1) # do not seem to be many in control group
remove(china)

data <- rbind(data, make.data(china.t1att1, china.t2att1, "china", 0, 18, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att2, china.t2att2, "china", 0, 19, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att3, china.t2att3, "china", 0, 20, 1, china.salience.T1K)) # t1 and t2 slight neg cor
data <- rbind(data, make.data(china.t1att4, china.t2att4, "china", 0, 21, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att5, china.t2att5, "china", 0, 22, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att6, china.t2att6, "china", 0, 23, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att7, china.t2att7, "china", 0, 24, 1, china.salience.T1K)) # t1 and t2 slight neg cor
data <- rbind(data, make.data(china.t1att8, china.t2att8, "china", 0, 25, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att9, china.t2att9, "china", 0, 26, 1, china.salience.T1K))
data <- rbind(data, make.data(china.t1att10, china.t2att10, "china", 0, 27, 1, china.salience.T1K))


#4	Greece
setwd("c:/users/pete/dropbox/cdd/data/Greece/data/")
greece <- spss("greece_data_all_final.sav")
greece.salience.T1K <- mean(greece$knowt1)
remove(greece)

data <- rbind(data, make.data(greece.t1att1, greece.t2att1, "greece", 0, 28, 1, greece.salience.T1K))
data <- rbind(data, make.data(greece.t1att2, greece.t2att2, "greece", 0, 29, 1, greece.salience.T1K))
data <- rbind(data, make.data(greece.t1att3, greece.t2att3, "greece", 0, 30, 1, greece.salience.T1K))
data <- rbind(data, make.data(greece.t1att4, greece.t2att4, "greece", 0, 31, 1, greece.salience.T1K))
data <- rbind(data, make.data(greece.t1att5, greece.t2att5, "greece", 0, 32, 1, greece.salience.T1K))
data <- rbind(data, make.data(greece.t1att6, greece.t2att6, "greece", 0, 33, 1, greece.salience.T1K))


#5	UK Crime
setwd("c:/users/pete/dropbox/cdd/data/British Crime/")
ukcrime <- spss("uk-crime.sav")
uk.crime.salience.T1K <- mean(ukcrime$pk1)
remove(ukcrime)

data <- rbind(data, make.data(ukcrime.policet1, ukcrime.policet2, "UK Crime", 0, 34, 0, uk.crime.salience.T1K))
data <- rbind(data, make.data(ukcrime.procrightst1, ukcrime.procrightst2, "UK Crime", 0, 35, 0, uk.crime.salience.T1K))
data <- rbind(data, make.data(ukcrime.punisht1, ukcrime.punisht2, "UK Crime", 0, 36, 0, uk.crime.salience.T1K))
data <- rbind(data, make.data(ukcrime.rootcauset1, ukcrime.rootcauset2, "UK Crime", 0, 37, 0, uk.crime.salience.T1K))
data <- rbind(data, make.data(ukcrime.selfprotectt1, ukcrime.selfprotectt2, "UK Crime", 0, 38, 0, uk.crime.salience.T1K))

#6	UK Europe
setwd("c:/users/pete/dropbox/cdd/data/British Europe/")
uk.eu <- spss("uk-eu.sav")
uk.eu.salience.T1K <- mean(uk.eu$pktot1)
remove(uk.eu)  

data <- rbind(data, make.data(ukeu.commies1r, ukeu.commies2r, "UK EU", 1, 39, 0, uk.eu.salience.T1K))
data <- rbind(data, make.data(ukeu.eurelat1g, ukeu.eurelat2g, "UK EU", 1, 40, 0, uk.eu.salience.T1K))
data <- rbind(data, make.data(ukeu.euscope1g, ukeu.euscope2g, "UK EU", 1, 41, 0, uk.eu.salience.T1K))
data <- rbind(data, make.data(ukeu.favref1r, ukeu.favref2r, "UK EU", 1, 42, 0, uk.eu.salience.T1K))


#7	UK General Election
setwd("c:/users/pete/dropbox/cdd/data/British General Election/")
bge <- spss("ukbge.sav")
bge.salience.T1K <- mean(rowMeans(cbind(bge$knowa1, bge$knowb1, bge$knowc1)))
remove(bge)

data <- rbind(data, make.data(ukbge.t1eu, ukbge.t2eu, "UK GE", 1, 43, 0, bge.salience.T1K))
data <- rbind(data, make.data(ukbge.t1tax, ukbge.t2tax, "UK GE", 0, 44, 0, bge.salience.T1K))
data <- rbind(data, make.data(ukbge.t1redist, ukbge.t2redist, "UK GE", 0, 45, 0, bge.salience.T1K))
data <- rbind(data, make.data(ukbge.t1wage, ukbge.t2wage, "UK GE", 0, 46, 0, bge.salience.T1K))


#8	UK Health
setwd("c:/users/pete/dropbox/cdd/data/British Health/Helath_Data/")
bh <- spss("health1.sav")
bh.salience.T1K <- mean(bh$hknow1)
remove(bh)

data <- rbind(data, make.data(ukhealth.t1avgdis, ukhealth.t2avgdis, "UK Health", 0, 47, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1ctexpt, ukhealth.t2ctexpt, "UK Health", 0, 48, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1dispub, ukhealth.t2dispub, "UK Health", 0, 49, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1hlthfu, ukhealth.t2hlthfu, "UK Health", 0, 50, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1moresa, ukhealth.t2moresa, "UK Health", 0, 51, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1option, ukhealth.t2option, "UK Health", 0, 52, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1payhlt, ukhealth.t2payhlt, "UK Health", 0, 53, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1poora, ukhealth.t2poora, "UK Health", 0, 54, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1preven, ukhealth.t2preven, "UK Health", 0, 55, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1pritre, ukhealth.t2pritre, "UK Health", 0, 56, 0, bh.salience.T1K))
data <- rbind(data, make.data(ukhealth.t1severi, ukhealth.t2severi, "UK Health", 0, 57, 0, bh.salience.T1K))


#9	UK Monarchy
setwd("c:/users/pete/dropbox/cdd/data/British Monarchy/monarchy_data/")
uk.mon <- spss("monarchy1.sav")

uk.mon.salience.T1K <- mean(rowMeans(cbind(uk.mon$knowa1, uk.mon$knowb1, uk.mon$knowc1,
                                           uk.mon$knowd1, uk.mon$knowe1, uk.mon$knowf1, 
                                           uk.mon$knowg1, uk.mon$knowh1, uk.mon$knowi1
)))
remove(uk.mon)


data <- rbind(data, make.data(ukmonarchy.t1mpop, ukmonarchy.t2mpop, "UK Monarchy", 0, 58, 0, uk.mon.salience.T1K))
data <- rbind(data, make.data(ukmonarchy.t1pwrm, ukmonarchy.t2pwrm, "UK Monarchy", 0, 59, 0, uk.mon.salience.T1K))
data <- rbind(data, make.data(ukmonarchy.t1reflor, ukmonarchy.t2reflor, "UK Monarchy", 0, 60, 0, uk.mon.salience.T1K))
data <- rbind(data, make.data(ukmonarchy.t1supmon, ukmonarchy.t2supmon, "UK Monarchy", 0, 61, 0, uk.mon.salience.T1K))


#10  US NIC II (f2f FP)
setwd("c:/users/pete/dropbox/cdd/data/NIC_II/Master_Data/")
nic2 <- spss("data_rev.sav")

nic2.salience.T1K <- mean(oneistrue(nic2$kno3_a)) # there are additional knowledge items, need know right answer

remove(nic2)

data <- rbind(data, make.data(nic2.t1demo, nic2.t2demo, "NIC 2", 1, 62, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1envir, nic2.t2envir, "NIC 2", 1, 63, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1forai1, nic2.t2forai1, "NIC 2", 1, 64, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1global, nic2.t2global, "NIC 2", 1, 65, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1humrh2, nic2.t2humrh2, "NIC 2", 1, 66, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1inter, nic2.t2inter, "NIC 2", 1, 67, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1multi, nic2.t2multi, "NIC 2", 1, 68, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1trade_b, nic2.t2trade_b, "NIC 2", 1, 69, 0, nic2.salience.T1K))
data <- rbind(data, make.data(nic2.t1usseca, nic2.t2usseca, "NIC 2", 1, 70, 0, nic2.salience.T1K))


#11	US Gen Elec (2004)
setwd("c:/users/pete/dropbox/cdd/data/US 2004 General Election/data")
usGE2004 <- spss("dopall_final1.sav")
usGE2004.salience.T1K <- mean(rowMeans(cbind(oneistrue(subset(usGE2004$w1qb44, usGE2004$w1qb44>-3)), oneistrue(subset(usGE2004$w1qb45, usGE2004$w1qb45>-3)))))
remove(usGE2004)
# there are additional knowledge items, but don't know correct answer

data <- rbind(data, make.data(btp04.w4b42, btp04.w4f42, "BTP 2004 GE", 0, 71, 0, usGE2004.salience.T1K)) # services
data <- rbind(data, make.data(btp04.w4b45, btp04.w4f45, "BTP 2004 GE", 1, 72, 0, usGE2004.salience.T1K)) # UN / NATO
data <- rbind(data, make.data(btp04.w4b48, btp04.w4f48, "BTP 2004 GE", 1, 73, 0, usGE2004.salience.T1K)) # free trade v protectionism
data <- rbind(data, make.data(btp04.w4b51, btp04.w4f51, "BTP 2004 GE", 0, 74, 0, usGE2004.salience.T1K)) # security v rights of accused terrorists (no mention of foreign terrorists)
data <- rbind(data, make.data(btp04.w4b54, btp04.w4f54, "BTP 2004 GE", 0, 75, 0, usGE2004.salience.T1K)) # healthcare 
data <- rbind(data, make.data(btp04.w4b57, btp04.w4f57, "BTP 2004 GE", 0, 76, 0, usGE2004.salience.T1K)) # gay marriage


#12	US New Haven
newhaven.salience.T1K <- mean(subset(master$t1know, master$pollname=="New Haven"))
# only test group available!!!

data <- rbind(data, make.data(nh.t1endexp, nh.t2endexp, "New Haven", 0, 77, 1, newhaven.salience.T1K))
data <- rbind(data, make.data(nh.t1manvol, nh.t2manvol, "New Haven", 0, 78, 1, newhaven.salience.T1K))
data <- rbind(data, make.data(nh.t1volloc, nh.t2volloc, "New Haven", 0, 79, 1, newhaven.salience.T1K))


#13	US NIC I (online FP)
setwd("c:/users/pete/Dropbox/cdd/")
nic1 <- spss("nic123_r.sav")
nic.salience.T1K <- mean(nic1$know1)
remove(nic1)

data <- rbind(data, make.data(nic1.t1att1, nic1.t2att1, "nic1", 1, 80, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att2, nic1.t2att2, "nic1", 1, 81, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att3, nic1.t2att3, "nic1", 1, 82, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att4, nic1.t2att4, "nic1", 1, 83, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att5, nic1.t2att5, "nic1", 1, 84, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att6, nic1.t2att6, "nic1", 1, 85, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att7, nic1.t2att7, "nic1", 1, 86, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att8, nic1.t2att8, "nic1", 1, 87, 0, nic.salience.T1K))
data <- rbind(data, make.data(nic1.t1att9, nic1.t2att9, "nic1", 1, 88, 0, nic.salience.T1K))

#14	US Primaries (Online)
setwd("c:/users/pete/dropbox/cdd/data/US Online Primaries/")
usPR2004 <- spss("data/Dop2004_b1f1_Client_022604.sav")
q43 <- ifelse(usPR2004$f1q43==1, 1, 0)
q44 <- ifelse(usPR2004$f1q44==3, 1, 0)
q45 <- ifelse(usPR2004$f1q45==2, 1, 0)
q46 <- ifelse(usPR2004$f1q46==4, 1, 0)
US.primaries.salience.T1K <- mean(rowMeans(cbind(q43, q44, q45, q46), na.rm=TRUE), na.rm=TRUE)
remove(usPR2004)

data <- rbind(data, make.data(btp04pr.t1mindex, btp04pr.t2mindex, "BTP 2004 Pr.", 0, 89, 0, US.primaries.salience.T1K))
data <- rbind(data, make.data(btp04pr.t1services, btp04pr.t2services, "BTP 2004 Pr.", 0, 90, 0, US.primaries.salience.T1K))
data <- rbind(data, make.data(btp04pr.t1trade, btp04pr.t2trade, "BTP 2004 Pr.", 1, 91, 0, US.primaries.salience.T1K))

#15	US Utilities: CPL
setwd("c:/users/pete/dropbox/cdd/data/utilities/cpl/cpl_data/")
cpl <- foreign::read.dta("cpl2.dta")
cpl.salience.T1K <- mean(rowMeans(cbind(cpl$KNOWA1, cpl$KNOWB1, cpl$KNOWC1, cpl$KNOWD1, 
                                        cpl$KNOWE1)))
remove(cpl)

data <- rbind(data, make.data(cpl.t1buypwr, cpl.t2buypwr, "CPL", 0, 84, 1, cpl.salience.T1K))
data <- rbind(data, make.data(cpl.t1compet, cpl.t2compet, "CPL", 0, 85, 1, cpl.salience.T1K))
data <- rbind(data, make.data(cpl.t1fossil, cpl.t2fossil, "CPL", 0, 86, 1, cpl.salience.T1K))
data <- rbind(data, make.data(cpl.t1cons, cpl.t2cons, "CPL", 0, 87, 1, cpl.salience.T1K))
data <- rbind(data, make.data(cpl.t1poor, cpl.t2poor, "CPL", 0, 88, 1, cpl.salience.T1K))
data <- rbind(data, make.data(cpl.t1renew, cpl.t2renew, "CPL", 0, 89, 1, cpl.salience.T1K))
data <- rbind(data, make.data(cpl.t1res, cpl.t2res, "CPL", 0, 90, 1, cpl.salience.T1K))





#16	US Utilities: SWEPCO
setwd("c:/users/pete/dropbox/cdd/data/utilities/swepco/swepco_data")
swepco <- foreign::read.dta("swepco2.dta")
swepco.salience.T1K <- mean(rowMeans(cbind(swepco$KNOWA1, swepco$KNOWB1, swepco$KNOWC1, swepco$KNOWD1, swepco$KNOWE1)))
remove(swepco)

data <- rbind(data, make.data(swepco.t1att1, swepco.t2att1, "swepco", 0, 91, 1, swepco.salience.T1K))
data <- rbind(data, make.data(swepco.t1att2, swepco.t2att2, "swepco", 0, 92, 1, swepco.salience.T1K))
data <- rbind(data, make.data(swepco.t1att3, swepco.t2att3, "swepco", 0, 93, 1, swepco.salience.T1K))
data <- rbind(data, make.data(swepco.t1att4, swepco.t2att4, "swepco", 0, 94, 1, swepco.salience.T1K))
data <- rbind(data, make.data(swepco.t1att5, swepco.t2att5, "swepco", 0, 95, 1, swepco.salience.T1K))
data <- rbind(data, make.data(swepco.t1att6, swepco.t2att6, "swepco", 0, 96, 1, swepco.salience.T1K))
data <- rbind(data, make.data(swepco.t1att7, swepco.t2att7, "swepco", 0, 97, 1, swepco.salience.T1K))

swepco$SOURCE1

#17	US Utilities: WTU  
setwd("c:/users/pete/dropbox/cdd/data/utilites/wt/wt_data/")
wtu <- foreign::read.dta("wt2.dta")
wtu.salience.T1K <- mean(rowMeans(cbind(wtu$KNOWA1, wtu$KNOWB1, wtu$KNOWC1, wtu$KNOWD1, wtu$KNOWE1)))
remove(wtu)

data <- rbind(data, make.data(wtu.t1att1, wtu.t2att1, "wtu", 0, 91, 1, wtu.salience.T1K))
data <- rbind(data, make.data(wtu.t1att2, wtu.t2att2, "wtu", 0, 92, 1, wtu.salience.T1K))
data <- rbind(data, make.data(wtu.t1att3, wtu.t2att3, "wtu", 0, 93, 1, wtu.salience.T1K))
data <- rbind(data, make.data(wtu.t1att4, wtu.t2att4, "wtu", 0, 94, 1, wtu.salience.T1K))
data <- rbind(data, make.data(wtu.t1att5, wtu.t2att5, "wtu", 0, 95, 1, wtu.salience.T1K))
data <- rbind(data, make.data(wtu.t1att6, wtu.t2att6, "wtu", 0, 96, 1, wtu.salience.T1K))
data <- rbind(data, make.data(wtu.t1att7, wtu.t2att7, "wtu", 0, 97, 1, wtu.salience.T1K))

#unique(master$pollname)
detach(master)

data <- as.data.frame(data)

data$id <- factor(data$id)
data$group <- factor(data$group)
data$issue <- factor(data$issue)
data$poll.id <- factor(data$poll.id, levels=unique(master$pollid), labels=unique(master$pollname))


data$country <- factor(data$country, levels=unique(data$country), labels=c("Australia", 
                                                                                 "Bulgaria",
                                                                                 "China",
                                                                                  "Greece",
                                                                                 "UK",
                                                                                 "US"))

setwd("c:/users/pete/dropbox/cdd/data/")
save(data, file="groupleveldataframe.rdata")

#################################################################################
################## INDIVIDUAL LEVEL DATA ##########################################
######################################################################################

attach(master) # if needed

#1  Australia Referendum

data.i <- make.data.i(aus.autind1, aus.autind2, poll="AU Monarchy", 0, 1, 0, aus.salience.t1K)  # national autonomy
data.i <- rbind(data.i, make.data.i(aus.demind1, aus.demind2, "AU Monarchy", 0, 2, 0, aus.salience.t1K)) # democracy
data.i <- rbind(data.i, make.data.i(aus.polind1, aus.polind2, "AU Monarchy", 0, 3, 0, aus.salience.t1K)) # politicization
data.i <- rbind(data.i, make.data.i(aus.tradind1, aus.tradind2, "AU Monarchy", 0, 4, 0, aus.salience.t1K)) #tradition
data.i <- rbind(data.i, make.data.i(aus.workind1, aus.workind2, "AU Monarchy", 0, 5, 0, aus.salience.t1K)) #workability


#2  Bulgaria 
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1clibe, bulgaria.bulgaria.t2clibe, "Bulgaria", 0, 6, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q10_3, bulgaria.bulgaria.t2q10_3, "Bulgaria", 0, 7, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q16, bulgaria.bulgaria.t2q16, "Bulgaria", 0, 8, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q19, bulgaria.bulgaria.t2q19, "Bulgaria", 0, 9, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q21, bulgaria.bulgaria.t2q21, "Bulgaria", 0, 10, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q22, bulgaria.bulgaria.t2q22, "Bulgaria", 0, 11, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q23, bulgaria.bulgaria.t2q23, "Bulgaria", 0, 12, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q8_1, bulgaria.bulgaria.t2q8_1, "Bulgaria", 0, 13, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q8_11, bulgaria.bulgaria.t2q8_11, "Bulgaria", 0, 14, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q8_7, bulgaria.bulgaria.t2q8_7, "Bulgaria", 0, 15, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1q8_8, bulgaria.bulgaria.t2q8_8, "Bulgaria", 0, 16, 0, bul.salience.T1K))
data.i <- rbind(data.i, make.data.i(bulgaria.bulgaria.t1tghpc, bulgaria.bulgaria.t2tghpc, "Bulgaria", 0, 17, 0, bul.salience.T1K))


#3  China
data.i <- rbind(data.i, make.data.i(china.t1att1, china.t2att1, "china", 0, 18, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att2, china.t2att2, "china", 0, 19, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att3, china.t2att3, "china", 0, 20, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att4, china.t2att4, "china", 0, 21, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att5, china.t2att5, "china", 0, 22, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att6, china.t2att6, "china", 0, 23, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att7, china.t2att7, "china", 0, 24, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att8, china.t2att8, "china", 0, 25, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att9, china.t2att9, "china", 0, 26, 1, china.salience.T1K))
data.i <- rbind(data.i, make.data.i(china.t1att10, china.t2att10, "china", 0, 27, 1, china.salience.T1K))


#4	Greece
data.i <- rbind(data.i, make.data.i(greece.t1att1, greece.t2att1, "greece", 0, 28, 1, greece.salience.T1K))
data.i <- rbind(data.i, make.data.i(greece.t1att2, greece.t2att2, "greece", 0, 29, 1, greece.salience.T1K))
data.i <- rbind(data.i, make.data.i(greece.t1att3, greece.t2att3, "greece", 0, 30, 1, greece.salience.T1K))
data.i <- rbind(data.i, make.data.i(greece.t1att4, greece.t2att4, "greece", 0, 31, 1, greece.salience.T1K))
data.i <- rbind(data.i, make.data.i(greece.t1att5, greece.t2att5, "greece", 0, 32, 1, greece.salience.T1K))
data.i <- rbind(data.i, make.data.i(greece.t1att6, greece.t2att6, "greece", 0, 33, 1, greece.salience.T1K))


#5	UK Crime
data.i <- rbind(data.i, make.data.i(ukcrime.policet1, ukcrime.policet2, "UK Crime", 0, 34, 0, uk.crime.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukcrime.procrightst1, ukcrime.procrightst2, "UK Crime", 0, 35, 0, uk.crime.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukcrime.punisht1, ukcrime.punisht2, "UK Crime", 0, 36, 0, uk.crime.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukcrime.rootcauset1, ukcrime.rootcauset2, "UK Crime", 0, 37, 0, uk.crime.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukcrime.selfprotectt1, ukcrime.selfprotectt2, "UK Crime", 0, 38, 0, uk.crime.salience.T1K))

#6	UK Europe
data.i <- rbind(data.i, make.data.i(ukeu.commies1r, ukeu.commies2r, "UK EU", 1, 39, 0, uk.eu.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukeu.eurelat1g, ukeu.eurelat2g, "UK EU", 1, 40, 0, uk.eu.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukeu.euscope1g, ukeu.euscope2g, "UK EU", 1, 41, 0, uk.eu.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukeu.favref1r, ukeu.favref2r, "UK EU", 1, 42, 0, uk.eu.salience.T1K))


#7	UK General Election
data.i <- rbind(data.i, make.data.i(ukbge.t1eu, ukbge.t2eu, "UK GE", 1, 43, 0, bge.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukbge.t1tax, ukbge.t2tax, "UK GE", 0, 44, 0, bge.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukbge.t1redist, ukbge.t2redist, "UK GE", 0, 45, 0, bge.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukbge.t1wage, ukbge.t2wage, "UK GE", 0, 46, 0, bge.salience.T1K))


#8	UK Health
data.i <- rbind(data.i, make.data.i(ukhealth.t1avgdis, ukhealth.t2avgdis, "UK Health", 0, 47, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1ctexpt, ukhealth.t2ctexpt, "UK Health", 0, 48, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1dispub, ukhealth.t2dispub, "UK Health", 0, 49, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1hlthfu, ukhealth.t2hlthfu, "UK Health", 0, 50, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1moresa, ukhealth.t2moresa, "UK Health", 0, 51, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1option, ukhealth.t2option, "UK Health", 0, 52, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1payhlt, ukhealth.t2payhlt, "UK Health", 0, 53, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1poora, ukhealth.t2poora, "UK Health", 0, 54, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1preven, ukhealth.t2preven, "UK Health", 0, 55, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1pritre, ukhealth.t2pritre, "UK Health", 0, 56, 0, bh.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukhealth.t1severi, ukhealth.t2severi, "UK Health", 0, 57, 0, bh.salience.T1K))


#9	UK Monarchy
data.i <- rbind(data.i, make.data.i(ukmonarchy.t1mpop, ukmonarchy.t2mpop, "UK Monarchy", 0, 58, 0, uk.mon.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukmonarchy.t1pwrm, ukmonarchy.t2pwrm, "UK Monarchy", 0, 59, 0, uk.mon.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukmonarchy.t1reflor, ukmonarchy.t2reflor, "UK Monarchy", 0, 60, 0, uk.mon.salience.T1K))
data.i <- rbind(data.i, make.data.i(ukmonarchy.t1supmon, ukmonarchy.t2supmon, "UK Monarchy", 0, 61, 0, uk.mon.salience.T1K))


#10  US NIC II (f2f FP)
data.i <- rbind(data.i, make.data.i(nic2.t1demo, nic2.t2demo, "NIC 2", 1, 62, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1envir, nic2.t2envir, "NIC 2", 1, 63, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1forai1, nic2.t2forai1, "NIC 2", 1, 64, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1global, nic2.t2global, "NIC 2", 1, 65, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1humrh2, nic2.t2humrh2, "NIC 2", 1, 66, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1inter, nic2.t2inter, "NIC 2", 1, 67, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1multi, nic2.t2multi, "NIC 2", 1, 68, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1trade_b, nic2.t2trade_b, "NIC 2", 1, 69, 0, nic2.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic2.t1usseca, nic2.t2usseca, "NIC 2", 1, 70, 0, nic2.salience.T1K))


#11	US Gen Elec (2004)
data.i <- rbind(data.i, make.data.i(btp04.w4b42, btp04.w4f42, "BTP 2004 GE", 0, 71, 0, usGE2004.salience.T1K)) # services
data.i <- rbind(data.i, make.data.i(btp04.w4b45, btp04.w4f45, "BTP 2004 GE", 1, 72, 0, usGE2004.salience.T1K)) # UN / NATO
data.i <- rbind(data.i, make.data.i(btp04.w4b48, btp04.w4f48, "BTP 2004 GE", 1, 73, 0, usGE2004.salience.T1K)) # free trade v protectionism
data.i <- rbind(data.i, make.data.i(btp04.w4b51, btp04.w4f51, "BTP 2004 GE", 0, 74, 0, usGE2004.salience.T1K)) # security v rights of accused terrorists (no mention of foreign terrorists)
data.i <- rbind(data.i, make.data.i(btp04.w4b54, btp04.w4f54, "BTP 2004 GE", 0, 75, 0, usGE2004.salience.T1K)) # healthcare 
data.i <- rbind(data.i, make.data.i(btp04.w4b57, btp04.w4f57, "BTP 2004 GE", 0, 76, 0, usGE2004.salience.T1K)) # gay marriage


#12	US New Haven
data.i <- rbind(data.i, make.data.i(nh.t1endexp, nh.t2endexp, "New Haven", 0, 77, 1, newhaven.salience.T1K))
data.i <- rbind(data.i, make.data.i(nh.t1manvol, nh.t2manvol, "New Haven", 0, 78, 1, newhaven.salience.T1K))
data.i <- rbind(data.i, make.data.i(nh.t1volloc, nh.t2volloc, "New Haven", 0, 79, 1, newhaven.salience.T1K))


#13	US NIC I (online FP)
data.i <- rbind(data.i, make.data.i(nic1.t1att1, nic1.t2att1, "nic1", 1, 80, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att2, nic1.t2att2, "nic1", 1, 81, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att3, nic1.t2att3, "nic1", 1, 82, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att4, nic1.t2att4, "nic1", 1, 83, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att5, nic1.t2att5, "nic1", 1, 84, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att6, nic1.t2att6, "nic1", 1, 85, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att7, nic1.t2att7, "nic1", 1, 86, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att8, nic1.t2att8, "nic1", 1, 87, 0, nic.salience.T1K))
data.i <- rbind(data.i, make.data.i(nic1.t1att9, nic1.t2att9, "nic1", 1, 88, 0, nic.salience.T1K))

#14	US Primaries (Online)
data.i <- rbind(data.i, make.data.i(btp04pr.t1mindex, btp04pr.t2mindex, "BTP 2004 Pr.", 0, 89, 0, US.primaries.salience.T1K))
data.i <- rbind(data.i, make.data.i(btp04pr.t1services, btp04pr.t2services, "BTP 2004 Pr.", 0, 90, 0, US.primaries.salience.T1K))
data.i <- rbind(data.i, make.data.i(btp04pr.t1trade, btp04pr.t2trade, "BTP 2004 Pr.", 1, 91, 0, US.primaries.salience.T1K))

#15	US Utilities: CPL
data.i <- rbind(data.i, make.data.i(cpl.t1buypwr, cpl.t2buypwr, "CPL", 0, 84, 1, cpl.salience.T1K))
data.i <- rbind(data.i, make.data.i(cpl.t1compet, cpl.t2compet, "CPL", 0, 85, 1, cpl.salience.T1K))
data.i <- rbind(data.i, make.data.i(cpl.t1fossil, cpl.t2fossil, "CPL", 0, 86, 1, cpl.salience.T1K))
data.i <- rbind(data.i, make.data.i(cpl.t1cons, cpl.t2cons, "CPL", 0, 87, 1, cpl.salience.T1K))
data.i <- rbind(data.i, make.data.i(cpl.t1poor, cpl.t2poor, "CPL", 0, 88, 1, cpl.salience.T1K))
data.i <- rbind(data.i, make.data.i(cpl.t1renew, cpl.t2renew, "CPL", 0, 89, 1, cpl.salience.T1K))
data.i <- rbind(data.i, make.data.i(cpl.t1res, cpl.t2res, "CPL", 0, 90, 1, cpl.salience.T1K))


#16	US Utilities: SWEPCO
data.i <- rbind(data.i, make.data.i(swepco.t1att1, swepco.t2att1, "swepco", 0, 91, 1, swepco.salience.T1K))
data.i <- rbind(data.i, make.data.i(swepco.t1att2, swepco.t2att2, "swepco", 0, 92, 1, swepco.salience.T1K))
data.i <- rbind(data.i, make.data.i(swepco.t1att3, swepco.t2att3, "swepco", 0, 93, 1, swepco.salience.T1K))
data.i <- rbind(data.i, make.data.i(swepco.t1att4, swepco.t2att4, "swepco", 0, 94, 1, swepco.salience.T1K))
data.i <- rbind(data.i, make.data.i(swepco.t1att5, swepco.t2att5, "swepco", 0, 95, 1, swepco.salience.T1K))
data.i <- rbind(data.i, make.data.i(swepco.t1att6, swepco.t2att6, "swepco", 0, 96, 1, swepco.salience.T1K))
data.i <- rbind(data.i, make.data.i(swepco.t1att7, swepco.t2att7, "swepco", 0, 97, 1, swepco.salience.T1K))

#17	US Utilities: WTU  
data.i <- rbind(data.i, make.data.i(wtu.t1att1, wtu.t2att1, "wtu", 0, 91, 1, wtu.salience.T1K))
data.i <- rbind(data.i, make.data.i(wtu.t1att2, wtu.t2att2, "wtu", 0, 92, 1, wtu.salience.T1K))
data.i <- rbind(data.i, make.data.i(wtu.t1att3, wtu.t2att3, "wtu", 0, 93, 1, wtu.salience.T1K))
data.i <- rbind(data.i, make.data.i(wtu.t1att4, wtu.t2att4, "wtu", 0, 94, 1, wtu.salience.T1K))
data.i <- rbind(data.i, make.data.i(wtu.t1att5, wtu.t2att5, "wtu", 0, 95, 1, wtu.salience.T1K))
data.i <- rbind(data.i, make.data.i(wtu.t1att6, wtu.t2att6, "wtu", 0, 96, 1, wtu.salience.T1K))
data.i <- rbind(data.i, make.data.i(wtu.t1att7, wtu.t2att7, "wtu", 0, 97, 1, wtu.salience.T1K))

#unique(master$pollname)
detach(master)

data.i <- as.data.frame(data.i)
colnames(data.i)[4] <- "diversity"
colnames(data.i)[5] <- "extremity"
colnames(data.i)[10] <- "salience.to.group.T1PK"

data.i$country <- factor(data.i$country, levels=unique(data.i$country), labels=c("Australia", 
                                                                                 "Bulgaria",
                                                                                 "China",
                                                                                 "Greece",
                                                                                 "UK",
                                                                                 "US"))
data.i$issue <- factor(data.i$issue)
data.i$id <- factor(data.i$id)
data.i$group <- factor(data.i$group)
data.i$poll.id <- factor(data.i$poll.id, levels=unique(master$pollid), labels=unique(master$pollname))

setwd("c:/users/pete/dropbox/cdd/data/")
save(data.i, file="indleveldataframe.rdata")


